#Êý¾Ý¿â
mybatis:
  type-aliases-package : com.tomorrow.monitorbusi.Entity
spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/monitor?useUnicode=true&characterEncoding=utf-8
    username : admin
    password : admin

#pagehelper
pagehelper:
  helperDialect : mysql
  reasonable : true
  supportMethodsArguments : true
  params : count=countSql